# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samyak Datta
email: datta [dot] samyak [at] gmail.com
description: > # this means to ignore newlines until "baseurl:"
  D-326, Old Boys Hostel,
  IIIT-Hyderabad, Gacchibowli
  Hyderabad - 500032
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: blog/:year/:month/:title
twitter_username: samyakdatta
github_username:  samyak-268

# Build settings
markdown: kramdown
